name: VoidFlame-Menus
version: 1.0.0
main: net.voidflame.menus.VoidFlameMenusPlugin
description: Menus module for VoidFlame MC.
author: VoidFlame
website: https://github.com/alialghamdi6068/VoidFlame-Menus
api-version: '26.2'
load: POSTWORLD
depend: [VoidFlame-Core]

commands:
  menu:
    description: Open the VoidFlame main menu.
    usage: /menu
    permission: voidflame.menu

permissions:
  voidflame.menu:
    description: Open the main practice menu.
    default: true
